const lenovoLegionPro7 = {
  product: {
    color: "Grey",
    type: "Notebook",
    formFactor: "Clamshell",
    housingMaterial: "Aluminium",
  },
  display: {
    diagonal: "16 inch",
    refreshRate: "240 Hz",
    contrastRatio: "1200:1",
    brightness: "500 cd/m²",
    panelType: "IPS",
    hdType: "WQXGA",
    ledBacklight: true,
    touchscreen: false,
    resolution: "2560 x 1600 pixels",
    hdrTechnology: ["DisplayHDR 400", "Dolby Vision"],
    rgbColorSpace: "sRGB",
    colorGamut: "100%",
    nativeAspectRatio: "16:10",
    hdrSupported: true,
  },
  brand: "Lenovo",
  family: "Legion",
  model: {
    name: "Pro 7",
    partNumber: "82WQ005CUS",
    releaseDate: "13 February 2023",
  },
  eanUpcCode: ["0196804591148", "196804591148"],
  processor: {
    manufacturer: "Intel",
    family: "Intel Core i9",
    motherboardChipset: "Intel HM770",
    boostFrequency: "5.4 GHz",
    model: "i9-13900HX",
    cores: 24,
    cache: "36 MB",
    generation: "13th gen Intel Core i9",
    efficientCoreBoostFrequency: "3.9 GHz",
  },
  memory: {
    type: "DDR5-SDRAM",
    size: "32 GB",
    formFactor: "SO-DIMM",
    clockSpeed: "5600 MHz",
    slots: "2x SO-DIMM",
    maxInternalMemory: "32 GB",
    layout: "2 x 16 GB",
    channels: "Dual-channel",
  },
  graphics: {
    discreteMemoryType: "GDDR6",
    discreteManufacturer: "NVIDIA",
    onboard: true,
    discrete: true,
    discreteModel: "NVIDIA GeForce RTX 4090",
    onboardModel: "Intel UHD Graphics",
    discreteMemory: "16 GB",
  },
  storage: {
    totalCapacity: "1000 GB",
    ssdCount: 1,
    ssdCapacity: "1000 GB",
    ssdInterface: "PCI Express 4.0",
    ssdFormFactor: "M.2",
    cardReader: false,
    media: "SSD",
    nvme: true,
  },
  opticalDrive: {
    type: false,
  },
  networking: {
    ethernet: true,
    ethernetDataRates: "100, 1000 Mbit/s",
    wifiStandard: "Wi-Fi 6E (802.11ax)",
    wifiStandards: "Wi-Fi 6E (802.11ax)",
    antennaType: "2x2",
    bluetooth: true,
    bluetoothVersion: "5.1",
    wwan: false,
  },
  portsInterfaces: {
    usbGen1Ports: 4,
    usbGen2TypeCPorts: 1,
    usbPowerDelivery: true,
    usbSleepAndChargePorts: 1,
    comboPort: true,
    hdmiPorts: 1,
    ethernetPorts: 1,
    usbTypeCAltMode: true,
    usbSleepAndCharge: true,
    thunderbolt4Ports: 1,
    intelThunderbolt4: true,
  },
  audio: {
    builtInMic: true,
    builtInSpeakers: 2,
    audioSystem: "Nahimic Audio",
    speakerPower: "2 W",
    audioChip: "Realtek ALC3306",
    speakersManufacturer: "Harman Kardon",
    microphones: 2,
  },
  camera: {
    frontCamera: true,
    privacyCamera: true,
    frontCameraHDType: "Full HD",
    frontCameraResolution: "1920 x 1080 pixels",
  },
  keyboard: {
    numericKeypad: true,
    backlitColor: "RGB",
    backlit: true,
    pointingDevice: "Touchpad",
    language: "US English",
    backlitZone: "Per-key RGB",
  },
  software: {
    osInstalled: "Windows 11 Home",
    osLanguage: "English",
    osArchitecture: "64-bit",
  },
  battery: {
    technology: "Lithium Polymer (LiPo)",
    capacity: "99.9 Wh",
    fastCharging: true,
  },
  weightDimensions: {
    weight: "2.8 kg",
    rearHeight: "2.59 cm",
    frontHeight: "2.19 cm",
    depth: "262.1 mm",
    width: "363.4 mm",
  },
  power: {
    acAdapterPower: "330 W",
    acAdapterFrequency: "50 - 60 Hz",
    acAdapterInputVoltage: "100 - 240 V",
  },
  security: {
    fingerprintReader: false,
    tpm: true,
    passwordProtection: true,
    passwordProtectionType: ["BIOS", "HDD", "Power on", "Supervisor"],
    tpmVersion: "2.0",
  },
  otherFeatures: {
    antiGlareScreen: true,
  },
};

const gigabyteG5 = {
  design: {
    color: "Black",
    type: "Notebook",
    formFactor: "Clamshell",
    marketPositioning: "Gaming",
  },
  display: {
    diagonal: "15.6 inch",
    refreshRate: "240 Hz",
    panelType: "IPS",
    surface: "Matt",
    hdType: "Full HD",
    ledBacklight: true,
    touchscreen: false,
    resolution: "1920 x 1080 pixels",
    rgbColorSpace: "NTSC",
    colorGamut: "72%",
    nativeAspectRatio: "16:9",
    brand: "Gigabyte",
    modelName: "G5 KC-8PT2130SH",
    partNumber: "9RC45KC03FE121PT001",
    releaseDate: "11 February 2021",
    eanUpcCode: "4719331813604",
  },
  processor: {
    manufacturer: "Intel",
    family: "10th gen Intel Core i7",
    frequency: "2.2 GHz",
    boostFrequency: "5 GHz",
    model: "i7-10870H",
    cores: 8,
    cache: "16 MB",
  },
  memory: {
    type: "DDR4-SDRAM",
    size: "16 GB",
    slots: "2x SO-DIMM",
    maxInternalMemory: "64 GB",
  },
  graphics: {
    onboardGraphics: true,
    nvidiaMaxQ: true,
    onboard4KSupport: true,
    onboardFamily: "Intel UHD Graphics",
    openGLSupport: true,
    discreteMemoryType: "GDDR6",
    discreteGraphics: true,
    discreteModel: "NVIDIA GeForce RTX 3060",
    discreteManufacturer: "NVIDIA",
    discreteMemory: "6 GB",
  },
  storage: {
    totalCapacity: "512 GB",
    ssdCapacity: "512 GB",
    compatibleMemoryCards: "SD",
    cardReader: true,
    media: "SSD",
  },
  opticalDrive: {
    type: false,
  },
  networking: {
    ethernet: true,
    ethernetDataRates: "10, 100, 1000, 2500 Mbit/s",
    wlanControllerModel: "Intel Wi-Fi 6 AX200",
    topWifiStandard: "Wi-Fi 6 (802.11ax)",
    wifiStandards: [
      "802.11a",
      "802.11b",
      "802.11g",
      "Wi-Fi 4 (802.11n)",
      "Wi-Fi 5 (802.11ac)",
      "Wi-Fi 6 (802.11ax)",
    ],
    wifiDataRateMax: "2400 Mbit/s",
    antennaType: "2x2",
    bluetooth: true,
    bluetoothVersion: "5.0",
  },
  portsInterfaces: {
    usbGen1Ports: 1,
    usbGen2Ports: 1,
    usbGen2TypeCPorts: 1,
    chargingPortType: "DC-in jack",
    microphoneIn: true,
    hdmiVersion: "2.0",
    comboPort: true,
    usb2Ports: 1,
    hdmiPorts: 1,
    ethernetPorts: 1,
    usbTypeCAltMode: true,
    miniDisplayPorts: 1,
  },
  audio: {
    builtInMic: true,
    builtInSpeakers: 2,
    audioSystem: "Nahimic 3",
    speakerPower: "2 W",
    microphones: 2,
  },
  camera: {
    frontCamera: true,
    frontCameraHDType: "HD",
  },
  keyboard: {
    numericKeypad: true,
    backlitColor: "RGB",
    backlit: true,
    pointingDevice: "Touchpad",
    language: "Portuguese",
  },
  software: {
    osInstalled: "Windows 10 Home",
    osArchitecture: "64-bit",
  },
  battery: {
    technology: "Lithium Polymer (LiPo)",
    capacity: "48.96 Wh",
  },
  weightDimensions: {
    weight: "2.2 kg",
    height: "27.9 mm",
    depth: "258 mm",
    width: "361 mm",
  },
  power: {
    acAdapterPower: "180 W",
    acAdapterFrequency: "50 - 60 Hz",
    acAdapterInputVoltage: "100 - 240 V",
  },
  security: {
    tpm: true,
  },
  otherFeatures: {
    antiGlareScreen: true,
  },
};

const asusLaptops = {
  zephyrusG14: {
    design: {
      color: "Grey",
      type: "Laptop",
      formFactor: "Clamshell",
      marketPositioning: "Gaming",
    },
    display: {
      diagonal: "14 inch",
      refreshRate: "120 Hz",
      panelType: "IPS",
      surface: "Matt",
      aspectRatio: "16:9",
      hdType: "Full HD",
      ledBacklight: true,
      touchscreen: false,
      resolution: "1920 x 1080 pixels",
      nativeAspectRatio: "16:9",
      brand: "ASUS",
      family: "ROG",
      series: "Zephyrus G14",
      modelName: "GA401IV-HE253T",
      partNumber: "90NR03F6-M07210",
      releaseDate: "01 May 2020",
    },
    processor: {
      manufacturer: "AMD",
      family: "AMD Ryzen 7",
      frequency: "2.9 GHz",
      boostFrequency: "4.2 GHz",
      model: "4800HS",
      cores: 8,
    },
    memory: {
      type: "DDR4-SDRAM",
      size: "16 GB",
      clockSpeed: "3200 MHz",
      slots: "1x SO-DIMM",
      maxInternalMemory: "32 GB",
    },
    graphics: {
      onboardGraphics: true,
      discreteMemoryType: "GDDR6",
      discreteGraphics: true,
      discreteModel: "NVIDIA GeForce RTX 2060 Max-Q",
      discreteMemory: "6 GB",
      onboardGraphicsCard: true,
      discreteGraphicsCard: true,
      onboardGraphicsModel: "AMD Radeon Graphics",
      discreteGraphicsModel: "NVIDIA GeForce RTX 2060 Max-Q",
      discreteGraphicsMemory: "6 GB",
    },
    storage: {
      totalCapacity: "512 GB",
      ssdCount: 1,
      ssdCapacity: "512 GB",
      totalSsdCapacity: "512 GB",
      ssdFormFactor: "M.2",
      cardReader: false,
      media: "SSD",
    },
    opticalDrive: {
      type: false,
    },
    networking: {
      ethernet: false,
      topWifiStandard: "Wi-Fi 6 (802.11ax)",
      wifiStandards: [
        "802.11a",
        "802.11b",
        "802.11g",
        "Wi-Fi 4 (802.11n)",
        "Wi-Fi 5 (802.11ac)",
        "Wi-Fi 6 (802.11ax)",
      ],
      bluetooth: true,
      bluetoothVersion: "5.0",
    },
    portsInterfaces: {
      usbGen1Ports: 2,
      usbGen2TypeCPorts: 2,
      hdmiVersion: "2.0b",
      comboPort: true,
      hdmiPorts: 1,
    },
    audio: {
      builtInMicrophone: true,
      builtInSpeakers: 4,
      audioSystem: "Dolby Atmos",
      speakerPower: "2.5 W",
    },
    keyboard: {
      numericKeypad: false,
      pointingDevice: "Touchpad",
      language: "German",
    },
    performance: {
      vrReady: true,
    },
    software: {
      osInstalled: "Windows 10 Home",
      osArchitecture: "64-bit",
    },
    weightDimensions: {
      weight: "1.7 kg",
      height: "19.9 mm",
      depth: "220 mm",
      width: "324 mm",
    },
    power: {
      acAdapterPower: "180 W",
    },
    security: {
      cableLockSlot: true,
      cableLockSlotType: "Kensington",
      passwordProtection: true,
      passwordProtectionType: ["BIOS", "User"],
    },
  },
  strixScar17: {
    design: {
      color: "Black",
      type: "Notebook",
      formFactor: "Clamshell",
      marketPositioning: "Gaming",
    },
    display: {
      diagonal: "17.3 inch",
      refreshRate: "300 Hz",
      brightness: "300 cd/m²",
      panelType: "IPS",
      surface: "Matt",
      hdType: "Full HD",
      touchscreen: false,
      resolution: "1920 x 1080 pixels",
      rgbColorSpace: "DCI-P3",
      colorGamut: "100%",
      nativeAspectRatio: "16:9",
      brand: "ASUS",
      family: "ROG",
      series: "Strix SCAR 17",
      modelName: "G733QS-HG125T",
      partNumber: "G733QS-HG125T",
      releaseDate: "22 March 2021",
      eanUpcCode: "4711081189909",
    },
    processor: {
      manufacturer: "AMD",
      family: "AMD Ryzen 9",
      frequency: "3.3 GHz",
      boostFrequency: "4.6 GHz",
      model: "5900HX",
      cores: 8,
      cache: "16 MB",
    },
    memory: {
      type: "DDR4-SDRAM",
      size: "16 GB",
      formFactor: "SO-DIMM",
      clockSpeed: "3200 MHz",
      slots: "2x SO-DIMM",
      maxInternalMemory: "64 GB",
    },
    graphics: {
      cuda: true,
      discreteMemoryType: "GDDR6",
      discreteGPUManufacturer: "NVIDIA",
      onboardGraphicsCard: true,
      discreteGraphicsCard: true,
      discreteGraphicsModel: "NVIDIA GeForce RTX 3080",
      onboardGraphicsModel: "AMD Radeon Graphics",
      discreteGraphicsMemory: "8 GB",
    },
    storage: {
      totalCapacity: "1000 GB",
      ssdCount: 1,
      ssdCapacity: "1000 GB",
      totalSsdCapacity: "1000 GB",
      ssdInterface: "NVMe, PCI Express 3.0",
      ssdFormFactor: "M.2",
      cardReader: false,
      media: "SSD",
    },
    opticalDrive: {
      type: false,
    },
    networking: {
      ethernet: true,
      ethernetDataRates: "10, 100, 1000 Mbit/s",
      topWifiStandard: "Wi-Fi 6 (802.11ax)",
      wifiStandards: [
        "802.11a",
        "802.11b",
        "802.11g",
        "Wi-Fi 4 (802.11n)",
        "Wi-Fi 5 (802.11ac)",
        "Wi-Fi 6 (802.11ax)",
      ],
      antennaType: "2x2",
      bluetooth: true,
      bluetoothVersion: "5.1",
    },
    portsInterfaces: {
      usbGen1Ports: 3,
      usbGen2TypeCPorts: 1,
      hdmiVersion: "2.0b",
      comboPort: true,
      hdmiPorts: 1,
      ethernetPorts: 1,
    },
    audio: {
      builtInMicrophone: true,
      builtInSpeakers: 4,
      speakerPower: "4 W",
    },
    keyboard: {
      numericKeypad: true,
      pointingDevice: "Touchpad",
    },
    software: {
      osInstalled: "Windows 10 Home",
      osArchitecture: "64-bit",
    },
    battery: {
      technology: "Lithium-Ion (Li-Ion)",
      capacity: "90 Wh",
      numberOfCells: 4,
    },
    weightDimensions: {
      weight: "2.7 kg",
      rearHeight: "2.75 cm",
      frontHeight: "2.34 cm",
      depth: "282 mm",
      width: "395 mm",
    },
    power: {
      acAdapterPower: "240 W",
      acAdapterFrequency: "50/60 Hz",
      acAdapterInputVoltage: "100 - 240 V",
      acAdapterOutputVoltage: "20 V",
      acAdapterOutputCurrent: "12 A",
    },
    security: {
      passwordProtection: true,
      passwordProtectionType: ["BIOS", "User"],
    },
  },
};
